services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:Enzo39824360@db:3306/escola_db
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Enzo39824360
      MYSQL_DATABASE: escola_db
    ports:
      - "3307:3306"